#############################################
### Query 1 - openId configuration
GET https://localhost:5001/.well-known/openid-configuration HTTP/1.1
### Query 2 - session status
GET https://localhost:5001/api/sessions/status HTTP/1.1
#############################################
